name: "godot-ci deploy"
on: push

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: LS
        run: |
          ls -ls
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/4.1.1.stable ~/.local/share/godot/templates/4.1.1.stable
      - name: LS
        run: |
          cd ~/.local/share/godot/templates/4.1.1.stable && echo "$PATH"
          cd /github/home/.local/share/godot/export_templates/4.1.1.stable/ && ls -ls
      - name: Web Build
        run: |
          mkdir -v -p builds/web
          godot -v --export-release --headless "Web" ../builds/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: builds/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: builds/web # The folder the action should deploy.
